### ISSUE TITLE
CWL CommandLineTool

### ISSUE THREAD

**Issue by tetron** [vsoch/scif#49]
Have you considered how this project might interact with a [Common Workflow Language](http://commonwl.org) (CWL) [CommandLineTool](https://www.commonwl.org/v1.0/CommandLineTool.html) description?

**Comment by vsoch** [comment]
No I haven't, but it's a great idea! I Imagine it would just correspond to interacting with the container as the binary, and then adding input arguments as needed?

```yaml
#!/usr/bin/env cwl-runner
cwlVersion: v1.0
class: CommandLineTool

label: An example run of a container with a scif filesystem
doc: This has not been tested, I wrote it in a Github issue !

inputs:
  message:
    label: the thing to echo
    type: string
    inputBinding:
      position: 1
outputs: []

baseCommand: [ exec, echo ]

s:author:
  - class: s:Person
    s:identifier: https://orcid.org/0000-0002-6130-1021
    s:email: mailto:dinosaur@avocado.email
    s:name: The Avocado Dinosaur
```

What did you have in mind, something more along the lines of providing a description internal to the container? Importantly, whatever is done we would want to either be programatically generated (ideal) OR really easy for the user to specify. Even starting with yaml adds a level of difficulty if you aren't used to the stringent space requirements, but anyway, really interested to hear your thoughts!
